### ISSUE TITLE
multiple definition of 'VideoSource's member function

### ISSUE THREAD

**Issue by hek14** [chrdiller/VideoMagnification#1]
When I build the whole project by Qt5, there is a error that says "error: multiple definition of `VideoSource::~VideoSource()'" and so does other memeber function of VideoSource. I double checked my .pro file, I didn't add the single file twice. So what's the issue about?

**Comment by chrdiller** [comment]
The thing is that I did not use QtCreator and qmake but instead used CMake as build system. So as you are not using the CMakeLists.txt, you have to manually decide whether to use V4L2 or not:

- If you don not want to use it (and instead the plain opencv variant), only include the video_opencv.cpp source file, not video_v4l2.cpp
- If you do want to try it, only include video_v4l2.cpp and define V4L2_CAPTURE to have the preprocessor include the helper header (needed in include/video_source.h)
